[registry]
default = "kellnr"

[registries.kellnr]
index = "sparse+https://reimagined-winner-p94grq576jh67gr-8000.app.github.dev/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "Zy9HhJ02RJmg0GCrgLfaCVfU6IwDfhXD"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
